name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ELM_HOME: ~/.elm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: npm ci
        env:
          NO_ELM_TOOLING_INSTALL: 1

      - name: Cache ELM_HOME
        uses: actions/cache@v5
        with:
          path: ${{ env.ELM_HOME }}
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'review/elm.json') }}
          restore-keys: elm-

      - run: npx elm-tooling install
      - run: npx elm make --docs docs.json
      - run: npx elm-format --validate src/
      - run: npx elm-review

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: npm ci
        env:
          NO_ELM_TOOLING_INSTALL: 1

      - name: Cache ELM_HOME
        uses: actions/cache@v5
        with:
          path: ${{ env.ELM_HOME }}
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'review/elm.json') }}
          restore-keys: elm-

      - run: npx elm-tooling install

      - name: Install example deps
        run: npm ci
        working-directory: example

      - name: Build Elm
        run: npx elm make src/Main.elm --optimize --output=static/elm.js
        working-directory: example

      - name: Bundle JS
        run: npx esbuild src/index.js --bundle --minify --outfile=static/main.js
        working-directory: example
